name: Deploy BE Staging

on:
    push:
        branches:
            - staging

jobs:
  deploy:
    name: Deploy BE to Vercel (Staging)
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      
      - name: Deploy BE to Vercel (Staging)
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_BACKEND_PROJECT_ID }}
          env: |
            SUPABASE_URL=${{ secrets.STAGING_DB_URL }}
            SUPABASE_KEY=${{ secrets.STAGING_DB_PASSWORD }}
          working-directory: ./backend
